baseURL: "https://haohan-lily-hu.github.io/"
title: "Haohan Lily Hu"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5 
        - name: Publications
          url: publications/
          weight: 4
        - name: Teaching
          url: teaching/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 5
        - name: Blog
          url: https://www.webofscience.com/wos/author/record/MSY-6982-2025
          weight: 2

params:
    description: "Personal academic website of Haohan Lily Hu."
    author: Haohan Lily Hu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research", "publications", "teaching", "CV", "blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Haohan Lily Hu
          subtitle: "Welcome to my home page! My name is Haohan Lily Hu; I am a Ph.D. candidate of Journalism and Communication Studies at the University of Hong Kong. My research interest focus on comparative political communication, multimodal communication (text, image, video), and computational analysis of news discourse. Methodologically, I’m interested in computational social science, especially natural language processing, (multimodal) large language model, and visual analyses. I am experienced in 3D animation, VR game production, and programming languages such as Python, R, C#, and SQL. I also enjoy the process of learning and exploring novel facets of emerging technologies and media. I obtained my M.J. (Journalism) degree at the University of Hong Kong and B.Sc from the School of Creative Media at the City University of Hong Kong. Outside academia, I have worked as a journalism and communication intern at China Daily and Hong Kong Trade Development Council."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Publications
              url: publications/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf
            - name: Blog
              url: https://www.webofscience.com/wos/author/record/MSY-6982-2025

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:lilyhhhu@protonmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=5oeb85gAAAAJ
        - name: Web of Science
          url: https://www.webofscience.com/wos/author/record/MSY-6982-2025
        - name: LinkedIn
          url: https://www.linkedin.com/in/haohan-lily-hu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Haohan Lily Hu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2