baseURL: "https://haohan-lily-hu.github.io/"
title: "Haohan Lily Hu"
theme: PaperMod

# reference: https://weizhang-econ.github.io/ ## for her news section
# https://rosavandenende.github.io/ ## for her talks section

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Curriculum vitae
          url: cv.pdf
          weight: 2
        - name: About Me
          url: aboutme/
          weight: 3
        - name: Miscellaneous
          url: https://lilyhhwho.wixsite.com/huhaohanlily/animation
          weight: 4

params:
    description: "Personal academic website of Haohan Lily Hu."
    author: Haohan Lily Hu
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications", "CV", "aboutme", "miscellaneous"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Haohan Lily Hu
          subtitle: "Welcome to my page! I am a Ph.D. candidate in Communication at the <i>University of Hong Kong</i>.<br/><br/>My research interest focus on comparative <i><b>political communication</i></b> and computational analysis of <i><b>news discourse</i></b>. Methodologically, I’m interested in computational social science, especially <b><i>(multimodal) nlp</i></b>, <b><i>(vision-) language models</i></b>, and <b><i>computational visual analysis</i></b>."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Curriculum vitae
              url: cv.pdf
            - name: About me
              url: aboutme/
            - name: Miscellaneous
              url: https://lilyhhwho.wixsite.com/huhaohanlily/animation

    socialIcons:
        - name: Email
          url: mailto:lilyhhhu@protonmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=5oeb85gAAAAJ
        - name: Web of Science
          url: https://www.webofscience.com/wos/author/record/MSY-6982-2025
        - name: LinkedIn
          url: https://www.linkedin.com/in/haohan-lily-hu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Haohan Lily Hu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2